version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:8080"
    volumes: 
      - ./src:/app
    command: go run main.go
